// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adegqyvdxewcwgcdpowe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZWdxeXZkeGV3Y3dnY2Rwb3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4OTU4NTIsImV4cCI6MjA3MzQ3MTg1Mn0._oVKbas-ZjzvVMOqaitraNvcgTNlEUPnVDtFWWlrnk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});